server:
  port: 8000

spring:
  application:
    name: sso-server
  datasource:
    url: jdbc:mysql://localhost:3306/property?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=true
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver


